# class test:
#     def __init__(self, x):
#         self.x = x
#     # def __str__(self):
#     #     return f"value is {self.x}"
# t = test(5)
# print(t) 

#  ye kebl address dega output nhi 


class test:
    def __init__(self, x):
        self.x = x
    def __str__(self):
        return f"value is {self.x}"
t = test(5)
print(t) 

# ab readble output mila 
# __str__ () = object ko human formet me print ke liye
#__init__ python ka constructor hota hai

